import { Profile, SocialLink, Service, PortfolioItem } from '../types/database';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'profile-amina-dj',
    user_id: 'user-demo-amina',
    username: 'amina',
    first_name: 'Amina',
    last_name: 'Hassan',
    display_name: 'Amina Hassan',
    profile_photo_url: '/src/assets/images/amina_avatar_1791203166115.jpg',
    cover_photo_url: '/src/assets/images/portfolio_branding_1791201654227.jpg',
    headline: 'Creative Designer & Brand Strategist',
    bio: 'Crafting thoughtful digital interfaces, design systems, and visual identities for forward-thinking brands across Djibouti, East Africa, and globally.',
    phone: '+253 77 12 34 56',
    whatsapp: '+25377123456',
    email: 'amina@studio.dj',
    website: 'https://amina.design',
    location: 'Djibouti City, Djibouti',
    theme: 'amber',
    template: 'professional',
    button_style: 'rounded',
    background_style: 'subtle-mesh',
    is_published: true,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-03-20T14:30:00Z',
  },
  {
    id: 'profile-fatouma-dj',
    user_id: 'user-demo-fatouma',
    username: 'fatouma',
    first_name: 'Fatouma',
    last_name: 'Omar',
    display_name: 'Fatouma Omar',
    profile_photo_url: '/src/assets/images/fatouma_avatar_1791201643209.jpg',
    cover_photo_url: '/src/assets/images/portfolio_mobile_ui_1791201666741.jpg',
    headline: 'Content Creator & Visual Storyteller',
    bio: 'Documenting East African culture, modern editorial fashion, and leading digital creative campaigns that resonate across borders.',
    phone: '+253 77 89 01 23',
    whatsapp: '+25377890123',
    email: 'fatouma@content.dj',
    website: 'https://fatouma.dj',
    location: 'Djibouti City, Djibouti',
    theme: 'emerald',
    template: 'creator',
    button_style: 'pill',
    background_style: 'card-glow',
    is_published: true,
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-03-22T11:20:00Z',
  },
  {
    id: 'profile-mohamed-dj',
    user_id: 'user-demo-mohamed',
    username: 'mohamed',
    first_name: 'Mohamed',
    last_name: 'Ali',
    display_name: 'Mohamed Ali',
    profile_photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
    cover_photo_url: null,
    headline: 'Business Consultant & Tech Advisor',
    bio: 'Advising growing ventures on digital transformation, technology strategy, and scalable systems across East Africa.',
    phone: '+253 77 45 67 89',
    whatsapp: '+25377456789',
    email: 'mohamed@advisory.dj',
    website: 'https://mohamedali.dj',
    location: 'Djibouti & Remote',
    theme: 'blue',
    template: 'minimal',
    button_style: 'rounded',
    background_style: 'clean',
    is_published: true,
    created_at: '2026-02-10T12:00:00Z',
    updated_at: '2026-03-24T16:00:00Z',
  },
];

export const INITIAL_SOCIAL_LINKS: SocialLink[] = [
  // Amina's links
  {
    id: 'link-a1',
    profile_id: 'profile-amina-dj',
    platform: 'LinkedIn',
    url: 'https://linkedin.com/in/amina-hassan',
    display_order: 0,
    is_visible: true,
  },
  {
    id: 'link-a2',
    profile_id: 'profile-amina-dj',
    platform: 'Instagram',
    url: 'https://instagram.com/amina.creative',
    display_order: 1,
    is_visible: true,
  },
  {
    id: 'link-a3',
    profile_id: 'profile-amina-dj',
    platform: 'X',
    url: 'https://x.com/amina_design',
    display_order: 2,
    is_visible: true,
  },
  {
    id: 'link-a4',
    profile_id: 'profile-amina-dj',
    platform: 'Telegram',
    url: 'https://t.me/amina_design',
    display_order: 3,
    is_visible: true,
  },

  // Fatouma's links
  {
    id: 'link-f1',
    profile_id: 'profile-fatouma-dj',
    platform: 'Instagram',
    url: 'https://instagram.com/fatouma.creative',
    display_order: 0,
    is_visible: true,
  },
  {
    id: 'link-f2',
    profile_id: 'profile-fatouma-dj',
    platform: 'TikTok',
    url: 'https://tiktok.com/@fatouma_visuals',
    display_order: 1,
    is_visible: true,
  },
  {
    id: 'link-f3',
    profile_id: 'profile-fatouma-dj',
    platform: 'YouTube',
    url: 'https://youtube.com/@FatoumaStudio',
    display_order: 2,
    is_visible: true,
  },

  // Mohamed's links
  {
    id: 'link-m1',
    profile_id: 'profile-mohamed-dj',
    platform: 'LinkedIn',
    url: 'https://linkedin.com/in/mohamed-ali-consulting',
    display_order: 0,
    is_visible: true,
  },
  {
    id: 'link-m2',
    profile_id: 'profile-mohamed-dj',
    platform: 'X',
    url: 'https://x.com/mohamed_consult',
    display_order: 1,
    is_visible: true,
  },
  {
    id: 'link-m3',
    profile_id: 'profile-mohamed-dj',
    platform: 'Website',
    url: 'https://mohamedali.dj',
    display_order: 2,
    is_visible: true,
  },
];

export const INITIAL_SERVICES: Service[] = [
  // Amina's services
  {
    id: 'srv-a1',
    profile_id: 'profile-amina-dj',
    title: 'Brand Identity & Visual Systems',
    description: 'Distinctive logomarks, typography rules, brand guidelines, and stationery kits designed for international presence.',
    price: 'From $1,200',
    display_order: 0,
    is_visible: true,
  },
  {
    id: 'srv-a2',
    profile_id: 'profile-amina-dj',
    title: 'Web & Mobile App UI/UX Design',
    description: 'Intuitive user experiences, clickable Figma prototypes, and complete developer-ready design systems.',
    price: 'From $2,000',
    display_order: 1,
    is_visible: true,
  },
  {
    id: 'srv-a3',
    profile_id: 'profile-amina-dj',
    title: 'Design Advisory & UX Audit',
    description: 'Comprehensive 1-on-1 teardown of your existing digital product with actionable usability recommendations.',
    price: '$350 / session',
    display_order: 2,
    is_visible: true,
  },

  // Fatouma's services
  {
    id: 'srv-f1',
    profile_id: 'profile-fatouma-dj',
    title: 'Commercial & Editorial Photography',
    description: 'High-end campaign photography, model casting, and location art direction across Djibouti and the Horn of Africa.',
    price: 'Custom quote',
    display_order: 0,
    is_visible: true,
  },
  {
    id: 'srv-f2',
    profile_id: 'profile-fatouma-dj',
    title: 'Creative Direction & Campaign Launch',
    description: 'End-to-end concept development, visual narratives, and social-first video storytelling.',
    price: 'Retainer / Project',
    display_order: 1,
    is_visible: true,
  },

  // Mohamed's services
  {
    id: 'srv-m1',
    profile_id: 'profile-mohamed-dj',
    title: 'Strategic Growth & Operational Advisory',
    description: 'Guiding enterprise teams on market expansion, digital systems implementation, and business process automation.',
    price: '$120 / hr',
    display_order: 0,
    is_visible: true,
  },
  {
    id: 'srv-m2',
    profile_id: 'profile-mohamed-dj',
    title: 'Technology Roadmapping MVP Consultation',
    description: 'Comprehensive assessment to evaluate product viability, architecture choices, and go-to-market execution.',
    price: 'From $1,800',
    display_order: 1,
    is_visible: true,
  },
];

export const INITIAL_PORTFOLIO: PortfolioItem[] = [
  // Amina's portfolio
  {
    id: 'port-a1',
    profile_id: 'profile-amina-dj',
    title: 'Meridian Capital Brand Identity',
    description: 'Modern luxury corporate branding, stationery packaging, and digital style guide for an East African investment group.',
    image_url: '/src/assets/images/portfolio_branding_1791201654227.jpg',
    project_url: 'https://behance.net',
    display_order: 0,
    is_visible: true,
  },
  {
    id: 'port-a2',
    profile_id: 'profile-amina-dj',
    title: 'Somali & Afar Digital Banking App',
    description: 'Next-generation fintech mobile banking experience featuring multi-currency wallets, instant QR payments, and clean dark UI.',
    image_url: '/src/assets/images/portfolio_mobile_ui_1791201666741.jpg',
    project_url: 'https://dribbble.com',
    display_order: 1,
    is_visible: true,
  },

  // Fatouma's portfolio
  {
    id: 'port-f1',
    profile_id: 'profile-fatouma-dj',
    title: 'Red Sea Salt & Stone Exhibition',
    description: 'Editorial documentary photo series capturing the natural geological landscapes and workers of Lake Assal.',
    image_url: '/src/assets/images/portfolio_branding_1791201654227.jpg',
    project_url: 'https://instagram.com',
    display_order: 0,
    is_visible: true,
  },
  {
    id: 'port-f2',
    profile_id: 'profile-fatouma-dj',
    title: 'Nomad Fashion Collective 2026',
    description: 'Seasonal lookbook combining traditional woven textiles with contemporary streetwear cuts.',
    image_url: '/src/assets/images/portfolio_mobile_ui_1791201666741.jpg',
    project_url: 'https://fatouma.dj',
    display_order: 1,
    is_visible: true,
  },
];
